name: Docker

on:
  push:
    branches: [ 'debug' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build dockerignore
        run: make .dockerignore
      -
        name: Build and test
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          load: true
          tags: flicknow/blueskybot:test
          build-args: 'DEBUG=1'
          target: test
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          build-args: 'DEBUG=1'
          tags: flicknow/blueskybot:debug-latest,flicknow/blueskybot:debug-${{ github.sha }}

